### ISSUE TITLE
"Empty Response" after each game

### ISSUE THREAD

**Issue by artygrand** [ensingm2/saliengame_idler#25]

**Comment by Zazcallabah** [comment]
Which version of the script are you using? Have you tried changing planets?

**Comment by artygrand** [comment]
Last version. On each planet. After 1-3 game

**Comment by PredatorIWD** [comment]
Same here, it almost always works the first time when I reload the page and paste the script and then all rounds end with "Empty Response" logged.

**Comment by formigao** [comment]
script is working normal for me but IF you try to minimize the page playing it stops working.
you must leave the window open all the time.. kind of annoying now... used to work fine with the window minimized

**Comment by PredatorIWD** [comment]
I am now running the script in a VM while the tab is focused and it seems to be working 100% of the time. @formigao At least the VM can be minimized, but thank you for that info, I lost 2 days worth of XP but it's finally working now.

**Comment by ensingm2** [comment]
I'm working on an unrelated feature and seem to be triggering this bug pretty consistently using it. Hopefully the same fix applies and will allow the window to be backgrounded.

**Comment by ensingm2** [comment]
Pretty sure this is due to setTimeouts being used to wait, which get inaccurate when the window isn't in focus. The request times out because it got pushed outside the 'acceptable' range within 120s, and is considered invalid.

Should probably move to a poller & event times going forward.

**Comment by Zazcallabah** [comment]
Currently testing if pull request #32 fixes this, but it takes time to prove a negative. ^_^

**Comment by Zazcallabah** [comment]
Heads up, I found an important clue!

The api doesn't return error messages in the body, it returns it in an X header!

    x-error_message | That zone is captured

The problem isn't in the timeout function, the problem is that we use old zone data when we are looking for the best zone to go to.

**Comment by Zazcallabah** [comment]
#32 did not fix the problem, having high hopes for #36

**Comment by Zazcallabah** [comment]
OK, seeing cors errors, not sure if they are related.

getting them on the "https://community.steam-api.com/ITerritoryControlMinigameService/ReportScore/v0001/" request, which obviously halts the script. should we add an error property to the ajax call that restarts the script?

**Comment by Zazcallabah** [comment]
Also getting a bunch of cors errors on the GetPlanet endpoint, meaning this issue still isn't fixed.

Some requests to GetPlanet get the correct cors header from the api, though. This must be some temporary steam issue? Or maybe the api is rate limiting in a very roundabout way? There is no difference on the sending end between the requests that pass and the requests that fail.

**Comment by ensingm2** [comment]
If it's CORS, it's gotta be a steam server misconfig. We're making the requests from the same page the official game is, so we shouldn't be getting those.

**Comment by Zazcallabah** [comment]
This is the request we're doing

	GET https://community.steam-api.com/ITerritoryControlMinigameService/GetPlanet/v0001/?id=11
	Host: community.steam-api.com
	User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
	Accept: */*
	Accept-Language: en-US,en;q=0.5
	Accept-Encoding: gzip, deflate, br
	Referer: https://steamcommunity.com/saliengame/play/
	Origin: https://steamcommunity.com
	Connection: keep-alive

Sometimes we get this back

	200 OK
	access-control-allow-origin	https://steamcommunity.com
	access-control-expose-headers	X-eresult, X-error_message
	cache-control	public, max-age=3
	content-encoding	gzip
	content-length	13439
	content-type	application/json; charset=UTF-8
	date	Sat, 23 Jun 2018 21:24:09 GMT
	expires	Sat, 23 Jun 2018 21:24:12 GMT
	vary	Origin,accept-encoding
	x-eresult	1
	X-Firefox-Spdy	h2

with correct json data

and sometimes we get this

	200 OK
	cache-control	public, max-age=2
	content-encoding	gzip
	content-length	13974
	content-type	application/json; charset=UTF-8
	date	Sat, 23 Jun 2018 20:21:29 GMT
	expires	Sat, 23 Jun 2018 20:21:31 GMT
	vary	accept-encoding
	x-eresult	1
	X-Firefox-Spdy	h2

with an empty response (or firefox supresses the response because cors is missing)

The cors errors are grouped by endpoint - GetPlanet has them, but no other endpoint, and earlier I only got them on the ReportScore endpoint.

Time also seems to be a factor. I get one cors error every five minutes or so, then nothing for an hour, then cors errors for a few minutes, and so on.

**Comment by artygrand** [comment]
Looks like it fixed now? Thanks!

**Comment by ensingm2** [comment]
It's kind of fixed. The CORS errors still happen periodically, but they're at least handled better now. Glad things are working!

**Comment by ensingm2** [comment]
Closing this issue, we added better AJAX error handling for CORS as well, so _hopefully_ people shouldn't run into this much, despite steam server hiccups. feel free to re-open if it happens again.
